### PR TITLE
Use databroker>=1.2.1 and updates to testing

### PR DESCRIPTION
**Pull request by gfabbris**
This `intake` version breaks something in `databroker`, see https://github.com/bluesky/databroker/issues/645.

### CODE REVIEW

**Comment by gfabbris** [comment]
By the way, this will be fixed with `databroker` 1.2.1.

**Review by prjemian — APPROVED** [review]
LGTM

**Comment by gfabbris** [comment]
It turns out the `bluesky` team was much faster than me. This issue is fixed in `databroker`>=1.2.1, which is the required version now.

With the new intake version, running `catalog()` does not reload the catalogs list anymore, replaced it to `catalog.force_reload`.

**Comment by gfabbris** [comment]
I don't understand why the CI keeps failing. I ran the exact same steps in my machine and it works fine. Maybe a mac vs. linux issue?

**Comment by gfabbris** [comment]
The CIs run fine only if I run `databroker-unpack` in the command line before running `pytest` ([here](https://github.com/APS-4ID-POLAR/polartools/blob/cb1b53c87ec4eada2b388b1e088203c175a94adf/.github/workflows/python-package-conda.yml#L62)). 

I suspect this has something to do with creating/finding the `intake` catalog folder, which can be read from databroker as `databroker.catalog_search_path`. This problem doesn't come up if I run `pytest` in my machine. Also, note that the catalog created by `databroker-unpack` **is not** used in the tests.

I'm going to leave this as is for now.

**Pull request merged**
