### PR TITLE
Db tools

### PR DESCRIPTION
**Pull request by strempfer**

### CODE REVIEW

**Comment by gfabbris** [comment]
@strempfer: I could work on this now, but just want to be sure that you're not in the middle of changing something, otherwis e the commits can get messed up.

**Comment by gfabbris** [comment]
I added a `show_meta_2` in the last commit. The main aspect of it is that the metadata reading and printing are split (there is also a `collect_meta`). The idea is that, with `collect_meta`, it will strictly return the metadata you asked for, but `show_meta` will trim down things to look better.

I also used Pete's `pyRestTable` to print it:

```python
In [6]: show_meta_2(10, db, scan_to=20, meta_keys='short')
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| Scan # | motors         | scan_type | plan_name | init. pos. | final pos. | num_points | exit_status |
+========+================+===========+===========+============+============+============+=============+
| 10     | magnet_6T_taby | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 11     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 12     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 13     | None           | None      | qxscan    | None       | None       | 128        | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 14     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 15     | None           | None      | qxscan    | None       | None       | 141        | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 16     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 17     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 18     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
| 19     | magnet_6T_tabx | None      | rel_scan  | -0.2       | 0.2        | 40         | success     |
+--------+----------------+-----------+-----------+------------+------------+------------+-------------+
```

It has the advantage that it looks very nice. But it may create problems when the table gets too wide (although this may be problematic regardless).

**Comment by gfabbris** [comment]
One aspect of this is that our current metadata is not greatly consistent. For example, in the table printed above, the info in the "qxscan" is not very useful. We need to keep the metadata in mind when making plans...

**Comment by gfabbris** [comment]
@strempfer: Should we move `db_query` to `db_tools`?

**Comment by strempfer** [comment]
> @strempfer: Should we move `db_query` to `db_tools`?

Since it only applied to dbs this would be good.

**Comment by strempfer** [comment]
# TODO: I don't like this. We need better metadata.
Agree. I don't like this either. Just wanted to have something working. We should have metadata that are the same for all scans and scan types.

**Pull request merged**
