### PR TITLE
Load data review

### LINKED ISSUE #17: Review how kwargs are handled in the various functions of `load_data`
It is currently rather mysterious how this is done, and it can lead to confusion over which kwargs are needed. For example, to figure out what are the possible kwargs in
 https://github.com/APS-4ID-POLAR/polartools/blob/46632f833c24549ffcfd7237218cccbfbce36dc9/polartools/load_data.py#L424
one may need to go through `load_absorption`, `load_scan`, `load_table`.

### PR DESCRIPTION
**Pull request by gfabbris**
This is a reasonably large change to `load_data`. The function `load_data.load_table` is the preferred way to load the data, see its docstring for the options. All absorption-related loading functions were moved to the `absorption` module.

Closes #17.

@strempfer - Could you check if you'll need to change anything in the `diffraction` module? You may want to create something like `diffraction.load_xrd` that uses `load_data.load_table`, but gets the correct columns, see for instance: https://github.com/APS-4ID-POLAR/polartools/blob/4426d107f0b606647028119024edf92e7fa6ca85/polartools/absorption.py#L39
You can just modify this branch.

### CODE REVIEW

**Comment by strempfer** [comment]
In load_absorption, can you also not normalize to the monitor? I don't see how you ever can reach the 'else 1.0' statement in line 100.

**Comment by gfabbris** [comment]
That line is the equivalent of doing:
```
if monitor is None:
    y0 = 1.0
else:
    y0 = table[monitor]
```

**Comment by gfabbris** [comment]
Oh, I think I just realize your point. I added the default options after I first wrote this function, and that line became useless.

**Comment by strempfer** [comment]
It would be good to be able to read which type of specfile it is: fourc4ID or Bluesky, but somehow I don't manage to get this information with spec2nexus. This is necessary, since the column names are different.

**Comment by gfabbris** [comment]
@strempfer : See the new `load_data.is_Bluesky_specfile` function.

@prjemian : This function checks for a "Bluesky" comment on the file header, which works for how the files are currently generated. Would there be another (potentially better) marker?

**Comment by prjemian** [comment]
That's the marker I added to identify a Bluesky-authored SPEC data file.  (When SPEC writes the file, it uses the name of the executable in this same location, or so I believe.  Such as fourc or spec.)  

Is there a better, more robust way to identify a Bluesky-authored SPEC data file?

**Comment by gfabbris** [comment]
> Is there a better, more robust way to identify a Bluesky-authored SPEC data file?

I think this is good. I'm just asking in case you envision this changing in the future. 

As a side note, if one doesn't close/start a the data files correctly in SPEC it will not add the header... (for instance: [absorption.dat](https://github.com/APS-4ID-POLAR/polartools/blob/17-load_data-review/polartools/tests/data_for_test/absorption.dat)). This is why the function check whether the file is Bluesky-generated rather than checking if it is SPEC-generated.

**Comment by gfabbris** [comment]
I think this is ready to be merged. Anything else?

**Comment by strempfer** [comment]
Ok, done.

**Pull request merged**
